name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run build step
      run: |
        echo "Building the project..."
        ls

    - name: Send Slack notification
      if: always()
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{
          "text": "GitHub Actions CI Pipeline completed for devops-webapp\nStatus: ${{ job.status }}"
        }' \
        ${{ secrets.SLACK_WEBHOOK_URL }}


